#
#

language:
  php

php:
  - 5.3
  - 5.4

# set up composer
before_script:
  - curl -s https://getcomposer.org/installer | php
  - php ./assignment2/composer.phar -v -o update

# run the phpunit tests
script:
  - php ./vendor/bin/phpunit --coverage-text -c phpunit.xml
